export const SELECT_SVG_START = "SELECT_SVG_START";
export const SELECT_SVG_SUCCESS = "SELECT_SVG_SUCCESS";
export const SELECT_SVG_ERROR = "SELECT_SVG_ERROR";

export const CHANGE_SVG_BORDER_WIDTH_START = "CHANGE_SVG_BORDER_WIDTH_START";
export const CHANGE_SVG_BORDER_WIDTH_SUCCESS = "CHANGE_SVG_BORDER_WIDTH_SUCCESS";
export const CHANGE_SVG_BORDER_WIDTH_ERROR = "CHANGE_SVG_BORDER_WIDTH_ERROR";

export const CHANGE_SVG_BORDER_COLOR_START = "CHANGE_SVG_BORDER_COLOR_START";
export const CHANGE_SVG_BORDER_COLOR_SUCCESS = "CHANGE_SVG_BORDER_COLOR_SUCCESS";
export const CHANGE_SVG_BORDER_COLOR_ERROR = "CHANGE_SVG_BORDER_COLOR_ERROR";
